require 'shellwords'

platform :ios, '17.0'
use_frameworks!

def speech_xcframework_paths
  {
    simulator: '$(SRCROOT)/Pods/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64_x86_64-simulator',
    device: '$(SRCROOT)/Pods/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64'
  }
end

def patch_skrivdet_user_project(installer)
  installer.aggregate_targets
    .map(&:user_project)
    .compact
    .uniq
    .each do |project|
      project.targets.each do |target|
        next unless target.name == 'skrivDET'

        target.frameworks_build_phase.files.each do |build_file|
          file_ref = build_file.file_ref
          next unless file_ref&.path == 'Pods_skrivDET.framework'

          target.frameworks_build_phase.remove_build_file(build_file)
        end

        target.build_configurations.each do |config|
          %w[FRAMEWORK_SEARCH_PATHS SWIFT_INCLUDE_PATHS].each do |key|
            config.build_settings.delete(key)

            {
              key => ['$(inherited)'],
              "#{key}[sdk=iphonesimulator*]" => ['$(inherited)', speech_xcframework_paths[:simulator]],
              "#{key}[sdk=iphoneos*]" => ['$(inherited)', speech_xcframework_paths[:device]]
            }.each do |setting_key, values|
              existing_values = case config.build_settings[setting_key]
              when Array
                config.build_settings[setting_key].flat_map { |value| Shellwords.shellsplit(value.to_s) }
              when String
                Shellwords.shellsplit(config.build_settings[setting_key])
              when nil
                []
              else
                Array(config.build_settings[setting_key])
              end

              config.build_settings[setting_key] = (existing_values + values).uniq
            end
          end
        end
      end

      project.save
    end
end

target 'skrivDET' do
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '~> 1.43.0'
end

post_install do |installer|
  fallback_framework_script = lambda do |configuration|
    <<~SH.chomp
      if [[ "$CONFIGURATION" == "#{configuration}" ]]; then
        if [ -r "${PODS_XCFRAMEWORKS_BUILD_DIR}/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.framework" ]; then
          install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.framework"
        elif [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
          install_framework "${PODS_ROOT}/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64_x86_64-simulator/MicrosoftCognitiveServicesSpeech.framework"
        else
          install_framework "${PODS_ROOT}/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.xcframework/ios-arm64/MicrosoftCognitiveServicesSpeech.framework"
        fi
      fi
    SH
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end

  frameworks_script_path = File.join(
    __dir__,
    'Pods',
    'Target Support Files',
    'Pods-skrivDET',
    'Pods-skrivDET-frameworks.sh'
  )

  if File.exist?(frameworks_script_path)
    frameworks_script = File.read(frameworks_script_path)

    {
      'Debug' => fallback_framework_script.call('Debug'),
      'Release' => fallback_framework_script.call('Release')
    }.each do |configuration, replacement|
      original = <<~SH.chomp
        if [[ "$CONFIGURATION" == "#{configuration}" ]]; then
          install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/MicrosoftCognitiveServicesSpeech-iOS/MicrosoftCognitiveServicesSpeech.framework"
        fi
      SH

      frameworks_script.gsub!(original, replacement)
    end

    File.write(frameworks_script_path, frameworks_script)
  end

  %w[debug release].each do |configuration|
    xcconfig_path = File.join(
      __dir__,
      'Pods',
      'Target Support Files',
      'Pods-skrivDET',
      "Pods-skrivDET.#{configuration}.xcconfig"
    )
    next unless File.exist?(xcconfig_path)

    xcconfig = File.read(xcconfig_path)
    xcconfig.gsub!(
      ' "${PODS_XCFRAMEWORKS_BUILD_DIR}/MicrosoftCognitiveServicesSpeech-iOS"',
      ''
    )
    File.write(xcconfig_path, xcconfig)
  end
end

post_integrate do |installer|
  patch_skrivdet_user_project(installer)
end
